INSERT INTO Types (Type, Kind) VALUES
('DIFFICULTY_DEMIGOD', 'KIND_DIFFICULTY'),
('DIFFICULTY_OMNISCIENT', 'KIND_DIFFICULTY'),
('TRAIT_DIFFICULTY_DEMIGOD', 'KIND_TRAIT'),
('TRAIT_DIFFICULTY_OMNISCIENT', 'KIND_TRAIT');
	
-- Delete Deity first to get the order correct
DELETE FROM Difficulties WHERE DifficultyType="DIFFICULTY_DEITY";
INSERT INTO Difficulties (DifficultyType, Name) VALUES
('DIFFICULTY_DEMIGOD', 'LOC_DIFFICULTY_DEMIGOD_NAME'),
('DIFFICULTY_DEITY', 'LOC_DIFFICULTY_DEITY_NAME'),
('DIFFICULTY_OMNISCIENT', 'LOC_DIFFICULTY_OMNISCIENT_NAME');

INSERT INTO Traits (TraitType, Name, Description) VALUES
('TRAIT_DIFFICULTY_DEMIGOD', 'LOC_TRAIT_DIFFICULTY_DEMIGOD_NAME', 'LOC_PLACEHOLDER'),
('TRAIT_DIFFICULTY_OMNISCIENT', 'LOC_TRAIT_DIFFICULTY_OMNISCIENT_NAME', 'LOC_PLACEHOLDER');

INSERT INTO DifficultyTraits (DifficultyType, TraitType) VALUES
('DIFFICULTY_DEMIGOD', 'TRAIT_DIFFICULTY_DEMIGOD'),
('DIFFICULTY_OMNISCIENT', 'TRAIT_DIFFICULTY_OMNISCIENT');