
-- Nerfs human production
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_LEADER_MAJOR_CIV', 'TRAIT_NERF_HUMAN_PRODUCTION_DEITY'),
('TRAIT_LEADER_MAJOR_CIV', 'TRAIT_NERF_HUMAN_PRODUCTION_OMNISCIENT');

INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES
('TRAIT_NERF_HUMAN_PRODUCTION_DEITY', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',  'PLAYER_IS_HUMAN_DEITY'),
('TRAIT_NERF_HUMAN_PRODUCTION_OMNISCIENT', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',  'PLAYER_IS_HUMAN_OMNISCIENT');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('TRAIT_NERF_HUMAN_PRODUCTION_DEITY', 'YieldType', 'YIELD_PRODUCTION'),
('TRAIT_NERF_HUMAN_PRODUCTION_DEITY', 'Amount', -10),
('TRAIT_NERF_HUMAN_PRODUCTION_OMNISCIENT', 'YieldType', 'YIELD_PRODUCTION'),
('TRAIT_NERF_HUMAN_PRODUCTION_OMNISCIENT', 'Amount', -15);
	
-- Requirement sets
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
('PLAYER_IS_HUMAN_DEITY', 'REQUIREMENTSET_TEST_ALL'),
('PLAYER_IS_HUMAN_OMNISCIENT', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
('PLAYER_IS_HUMAN_DEITY', 'REQUIRES_PLAYER_IS_HUMAN'),
('PLAYER_IS_HUMAN_DEITY', 'REQUIRES_DEITY'),
('PLAYER_IS_HUMAN_OMNISCIENT', 'REQUIRES_PLAYER_IS_HUMAN'),
('PLAYER_IS_HUMAN_OMNISCIENT', 'REQUIRES_OMNISCIENT');